version: "3"
services:
  forstream:
    image: "forstream:latest"
    container_name: "forstream"
    volumes:
      - "./configs.yml:/usr/src/forstream/configs.yml"
      - "./public:/usr/src/forstream/public"
    ports:
      - "3000:3000"
networks:
  default:
    external:
      name: "forstream"
